### ISSUE TITLE
请教下cdma

### ISSUE THREAD

**Issue by andyhuai** [mbyzhang/sms2tg#1]
我现在有cdma的卡，之前用华为EC121试过gammu，无法获取SMSC，
最近买了EC20的卡，树莓派都能识别串口，但是gammu能读到IMEI，但是无法收发短信，还是 failed to get SMSC
查了下，电信的卡，好像没有SMSC这个中心码
用你的这个程序能实现收发短信吗？

**Comment by mbyzhang** [comment]
Hello

CDMA 的模块用的协议与 GSM 有一定区别，而 gammu 只支持 GSM 模块而非 CDMA 模块。我的这个程序目前支持 CDMA 模块的短信收发，你可以尝试一下我的程序

**Comment by andyhuai** [comment]
@mbyzhang 
是了下，没有反应，方便交流下吗

**Comment by andyhuai** [comment]
pi@raspberrypi:~/sms2tg $ python3 main.py
INFO:root:Starting sms2tg
DEBUG:root:> b'AT'
DEBUG:root:< b'AT\r\r\n'
DEBUG:root:> b'\r\n'
DEBUG:root:< b'OK\r\n'
DEBUG:root:> b'AT+CLIP=1'
DEBUG:root:< b'AT+CLIP=1\r\r\n'
DEBUG:root:> b'\r\n'
DEBUG:root:< b'OK\r\n'
INFO:root:init serial
INFO:root:Fetching unread messages
DEBUG:root:> b'AT+CMGL=4'
DEBUG:root:> b'\r\n'
DEBUG:root:< b'AT+CMGL=4\r\r\n'
DEBUG:root:< b'OK\r\n'
INFO:root:Polling new messages

**Comment by andyhuai** [comment]
INFO:root:Polling new messages
DEBUG:root:< b'\r\n'
DEBUG:root:< b'+CMTI: "SM",11\r\n'
DEBUG:root:Incoming SMS
DEBUG:root:SMS index is 11
DEBUG:root:> b'AT+CMGR=11'
DEBUG:root:> b'\r\n'
DEBUG:root:< b'AT+CMGR=11\r\r\n'
DEBUG:root:< b'OK\r\n'
DEBUG:root:['OK']
WARNING:root:
Traceback (most recent call last):
  File "/home/pi/sms2tg/at.py", line 101, in poll
    assert(len(result) == 4 and result[0].startswith('+CMGR'))
AssertionError

具体代码：
                if name == 'CMTI':
                    logging.debug('Incoming SMS')
                    index = int(args[1])
                    logging.debug('SMS index is {}'.format(index))
                    result = comm.execute('AT+CMGR={}'.format(index))
                    logging.debug(result)
                    assert(len(result) == 4 and result[0].startswith('+CMGR'))
                    handle_message(result[1], index)

像是没有找到短信，log打印是 DEBUG:root:['OK']，没有具体内容

**Comment by andyhuai** [comment]
又进了一步，能获取到短信了，但是解码错误
DEBUG:root:Incoming SMS
DEBUG:root:SMS index is 0
DEBUG:root:> b'AT+CMGR=0'
DEBUG:root:> b'\r\n'
DEBUG:root:< b'AT+CMGR=0\r\r\n'
DEBUG:root:< b'+CMGR: 0,,22\r\n'
DEBUG:root:< b'00000B817106175378F60000020132122350000331D90C\r\n'
DEBUG:root:< b'\r\n'
DEBUG:root:< b'OK\r\n'
DEBUG:root:['+CMGR: 0,,22', '00000B817106175378F60000020132122350000331D90C', '', 'OK']
WARNING:root:Unexpected PDU data

这个pdu码，我用在线解析出来了
SMSC#
Sender:176071XXXXXX
TimeStamp:23/10/20 21:32:05 GMT ?
TP_PID:00
TP_DCS:00
TP_DCS-popis:Uncompressed Text
No class
Alphabet:Default

123
Length:3

**Comment by mbyzhang** [comment]
Hello
刚看了一下你这个 PDU 应该是 GSM 格式的诶，我这个程序目前只支持 CDMA 格式的 PDU。理论上来讲 gammu 应该是可以用的，你可以把 gammu 完整 log 贴上来么？

**Comment by andyhuai** [comment]
WTF,
我一通AT改模式，居然可以发出去短信了~~~~~
